services:

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

    networks:
      - smart-network

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  scraper:
    build: ./scraper-service
    container_name: scraper-service

    depends_on:
      redis:
        condition: service_healthy

    env_file:
      - ./scraper-service/.env

    volumes:
      - ./scraper-service:/app

    environment:
      - PYTHONPATH=/app

    networks:
      - smart-network

    restart: unless-stopped

  ai-engine:
    build: ./ai-engine
    container_name: ai-engine

    ports:
      - "8000:8000"

    depends_on:
      redis:
        condition: service_healthy

    env_file:
      - ./ai-engine/.env

    networks:
      - smart-network

    restart: unless-stopped

  ai-worker:
    build: ./scraper-service
    container_name: ai-worker

    command: python services/ai_worker.py

    depends_on:
      redis:
        condition: service_healthy
      ai-engine:
        condition: service_started

    env_file:
      - ./scraper-service/.env

    volumes:
      - ./scraper-service:/app

    environment:
      - PYTHONPATH=/app

    networks:
      - smart-network

    restart: unless-stopped


networks:
  smart-network:
    driver: bridge