services:

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

    networks:
      - smart-network

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  scraper:
    build: ./scraper-service
    container_name: scraper-service

    depends_on:
      redis:
        condition: service_healthy

    env_file:
      - ./scraper-service/.env

    volumes:
      - ./scraper-service:/app

    environment:
      - PYTHONPATH=/app

    networks:
      - smart-network

    restart: unless-stopped

  ai-engine:
    build: ./ai-engine
    container_name: ai-engine

    ports:
      - "8000:8000"

    depends_on:
      redis:
        condition: service_healthy

    env_file:
      - ./ai-engine/.env

    volumes:
      - ai-engine-cache:/root/.cache/huggingface

    networks:
      - smart-network

    restart: unless-stopped

  ai-worker:
    build: ./scraper-service
    container_name: ai-worker

    command: python services/ai_worker.py

    depends_on:
      redis:
        condition: service_healthy
      ai-engine:
        condition: service_started
      backend:
        condition: service_healthy

    env_file:
      - ./scraper-service/.env

    # volumes:
    #   - ./scraper-service:/app

    environment:
      - PYTHONPATH=/app

    networks:
      - smart-network

    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend

    ports:
      - "3000:3000"

    env_file:
      - ./backend/.env

    depends_on:
      - redis

    networks:
      - smart-network

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 5s
      timeout: 3s
      retries: 5
    
    dns:
      - 8.8.8.8
      - 8.8.4.4

    restart: unless-stopped

networks:
  smart-network:
    name: smart-network
    driver: bridge

volumes:
  ai-engine-cache: